// src/mockData.js
const mockData = [
    {
      "_id": "665e17994cb8bc8f339b8e55",
      "end_year": "",
      "intensity": 6,
      "sector": "Retail",
      "topic": "export",
      "insight": "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
      "url": "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
      "region": "Northern America",
      "start_year": "",
      "impact": "",
      "added": "January, 17 2017 02:21:10",
      "published": "",
      "country": "United States of America",
      "relevance": 2,
      "pestle": "Economic",
      "source": "WSJ",
      "title": "More U.S. LNG (liquified natural gas) export capacity is expected to hit the market.",
      "likelihood": 3
    },
    {
      "_id": "665e17994cb8bc8f339b8e4e",
      "end_year": "",
      "intensity": 6,
      "sector": "",
      "topic": "market",
      "insight": "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
      "url": "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
      "region": "World",
      "start_year": "",
      "impact": "",
      "added": "January, 19 2017 00:55:54",
      "published": "January, 18 2017 00:00:00",
      "country": "",
      "relevance": 2,
      "pestle": "Economic",
      "source": "SBWire",
      "title": "Polymerization will remain top 3 end-users in global n-Hexane Market.",
      "likelihood": 3
    },
    {
      "_id": "665e17994cb8bc8f339b8e4c",
      "end_year": "",
      "intensity": 6,
      "sector": "Energy",
      "topic": "consumption",
      "insight": "Annual Energy Outlook",
      "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
      "region": "Northern America",
      "start_year": "",
      "impact": "",
      "added": "January, 20 2017 03:51:23",
      "published": "January, 09 2017 00:00:00",
      "country": "United States of America",
      "relevance": 2,
      "pestle": "Industries",
      "source": "EIA",
      "title": "U.S. petroleum consumption is projected to remain below the 2005 level.",
      "likelihood": 3
    },
    {
      "_id": "665e17994cb8bc8f339b8e4d",
      "end_year": "",
      "intensity": 6,
      "sector": "Environment",
      "topic": "oil",
      "insight": "WRI Partnership Aims to Foster Supply Chain Transparency, Zero-Deforestation Strategies",
      "url": "http://www.sustainablebrands.com/news_and_views/supply_chain/sustainable_brands/wri_partnership_aims_foster_supply_chain_transparency",
      "region": "Central America",
      "start_year": "",
      "impact": "",
      "added": "January, 20 2017 03:26:40",
      "published": "January, 18 2017 00:00:00",
      "country": "Mexico",
      "relevance": 3,
      "pestle": "Environmental",
      "source": "sustainablebrands.com",
      "title": "Mars, Unilever, Cargill and Mondelēz are already using GFW Commodities to assess deforestation risks in their palm oil, soy and cocoa supply chains across a collective area of land the size of Mexico.",
      "likelihood": 2
    },
    {
      "_id": "665e17994cb8bc8f339b8e58",
      "end_year": "",
      "intensity": 12,
      "sector": "Energy",
      "topic": "oil",
      "insight": "OPEC sees market stability in 2017, Venezuela aims for $70 price",
      "url": "http://www.reuters.com/article/us-venezuela-opec-idUSKBN1502JJ",
      "region": "Eastern Europe",
      "start_year": "",
      "impact": "",
      "added": "January, 17 2017 01:17:33",
      "published": "January, 17 2017 00:00:00",
      "country": "Russia",
      "relevance": 3,
      "pestle": "Industries",
      "source": "Reuters",
      "title": "OPEC, Russia and other non-members of the producer group will curtail oil output by nearly 1.8 million bpd.",
      "likelihood": 4
    },
    {
      "_id": "665e17994cb8bc8f339b8e5e",
      "end_year": "",
      "intensity": 8,
      "sector": "Financial services",
      "topic": "policy",
      "insight": "World Bank Forecasts Nigeria To Exit Recession In 2017",
      "url": "https://www.thenews.ng/2017/01/world-bank-forecasts-nigeria-to-exit-recession-in-2017/",
      "region": "Central Africa",
      "start_year": "",
      "impact": "",
      "added": "January, 15 2017 05:21:39",
      "published": "January, 13 2017 00:00:00",
      "country": "Angola",
      "relevance": 2,
      "pestle": "Economic",
      "source": "TheNews.NG",
      "title": "Angola is projected to expand at a moderate 1.2 percent pace as high inflation and tight policy continue to weigh on consumption and investment.",
      "likelihood": 4
    },
    {
      "_id": "665e17994cb8bc8f339b8e66",
      "end_year": "",
      "intensity": 6,
      "sector": "",
      "topic": "market",
      "insight": "US dollar moves dominated Sterling during the European session on Thursday.",
      "url": "https://www.pdqfx.com/latest-news/13-01-2017",
      "region": "World",
      "start_year": "",
      "impact": "",
      "added": "January, 15 2017 02:40:46",
      "published": "",
      "country": "",
      "relevance": 2,
      "pestle": "Political",
      "source": "PDQFX news",
      "title": "Brexit fears and global market trends will tend to dominate in the short term.",
      "likelihood": 3
    },
  ];
  
  export default mockData;
  